### ISSUE TITLE
broken map & other final week issues

### ISSUE THREAD

**Issue by sgar7** [CDRH/african_poetics#277] opened 2023-02-17 15:17 UTC
- [x] Poets: [cannot](https://africanpoetics.unl.edu/inthenews/poets) click on map. All maps should function like this [one](https://africanpoetics.unl.edu/contemporarypoets/browse/keywords). 
- [x] -  Education search: just list the name of the school ([remove](https://africanpoetics.unl.edu/inthenews/poets/browse/keywords) degree earned + unknown)

- [x] - If we click on the University, it should bring up all the people who went there.

- [x] - Search by nationality: [remove](https://africanpoetics.unl.edu/inthenews/poets/search?f%5B%5D=places%7CEngland) education and just list names

- [x] News: then [Browse by Decade](https://africanpoetics.unl.edu/inthenews/news/browse/topics): remove decimals

- [x] - [News Format](https://africanpoetics.unl.edu/inthenews/news/browse/type#): Advertisements, the first one (Multiple Classified Advertising Items). Link to related works is broken.

- [x] - Related works: [link is broken](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.work.000107)

- [x] Works: [remove](https://africanpoetics.unl.edu/inthenews/works) “African Poet” tab

- [x] - When you click on Author and get the list of news items, you should able to click and get the news item details

- [x] - This is there for some (Kofi) and not for others 

- [x] - [Search bar](https://africanpoetics.unl.edu/inthenews/works/search): what does this search? I don’t think this is working. Example: type in Kofi and 0 items show up

- [x] [About](https://africanpoetics.unl.edu/inthenews/about): get rid of “About African Poets and Poetry in the News” tab, move Credits tab to the bottom

**Comment by sgar7** [comment] 2023-02-17 15:18
News, then [Browse by Decade](https://africanpoetics.unl.edu/inthenews/news/browse/topics): remove decibels 
[News Format](https://africanpoetics.unl.edu/inthenews/news/browse/type#): Advertisements, the first one (Multiple Classified Advertising Items)
Related works: [link is broken](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.work.000107)

**Comment by sgar7** [comment] 2023-02-17 15:19
[About](https://africanpoetics.unl.edu/inthenews/about): get rid of “About African Poets and Poetry in the News” tab, move Credits tab to the bottom

**Comment by sgar7** [comment] 2023-02-17 15:34
**Contemporary African Poets**

Under browse by Poet - [remove](https://africanpoetics.unl.edu/contemporarypoets/browse/person.name) the count (1)
- Rather than A - Z, break it up into A - H, I - L etc. 
 
Under [browse by country](https://africanpoetics.unl.edu/contemporarypoets/browse/places): we need a country 1 and country 2 which has to be separated

**Comment by sgar7** [comment] 2023-02-17 17:31
Broken links:
[link 1](https://africanpoetics.unl.edu/inthenews/news/item/apdp.news.000013)%5BThose%20among%20you%20who%20like%20a%20good%20laugh%20now%20and%20again%20will%20be%20highly%20amused%20by%20the%20news%20that%20in%20two%20days%20times%20the%20International%20Olympics%20Committee%20will%20consider%20a%20request%20by%20South%20Africa%20to%20be%20allowed%20to%20complete%20in%20the%20next%20Olympics%20in%20Mexico%20(1967-04-30)%5D(apdp.news.000452)%5BReport%20indicts%20S%20African%20prisons%20(1967-07-02)%5D(apdp.news.000453)%5BHow%20readers%20reacted%20to%20Parkinson's%20article%20on%20the%20MCC%20Council%20(1969-02-02)%5D(apdp.news.000460)

**Comment by wkdewey** [comment] 2023-02-17 18:07
where are you seeing the last broken link?

**Comment by wkdewey** [comment] 2023-02-17 20:35
https://africanpoetics.unl.edu/inthenews/poets/item/apdp.work.000107 works should not be nested under poets. Is this link being generated somewhere? I don't see a broken link if I go to https://africanpoetics.unl.edu/inthenews/works/item/apdp.work.000107

**Comment by wkdewey** [comment] 2023-02-17 21:13
https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.000779 there is a broken link on news items, this is from the airtable side. I don't do any processing in Datura and most of the links work as is, except for the first one.

**Comment by wkdewey** [comment] 2023-02-17 21:20
> https://africanpoetics.unl.edu/inthenews/poets/item/apdp.work.000107 works should not be nested under poets. Is this link being generated somewhere? I don't see a broken link if I go to https://africanpoetics.unl.edu/inthenews/works/item/apdp.work.000107

this was caused by the wrong path being called in the view, fixed now

**Comment by wkdewey** [comment] 2023-02-17 22:28
> https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.000779 there is a broken link on news items, this is from the airtable side. I don't do any processing in Datura and most of the links work as is, except for the first one.

I can change the link parsing code so that it doesn't break, but there are still issues with what's coming from Airtable. In a string like the following:
```
"[Scorning the Sonnet (1983-09-16)](apdp.news.000013)[Those among you who like a good laugh now and again will be highly amused by the news that in two days times the International Olympics Committee will consider a request by South Africa to be allowed to complete in the next Olympics in Mexico (1967-04-30)](apdp.news.000452)[Report indicts S African prisons (1967-07-02)](apdp.news.000453)[How readers reacted to Parkinson's article on the MCC Council (1969-02-02)](apdp.news.000460)|Poet"
```
I changed the markdown parsing so it will only make a link out of the first part. But the Airtable tables should be changed so that all those markdown links aren't in the same string running together, as my assumption is that it will only receive one markdown link at a time.

**Comment by wkdewey** [comment] 2023-02-20 18:54
the browse by decade problem went away (at least on my end) after a new ingest

**Comment by wkdewey** [comment] 2023-02-20 19:24
> When you click on Author and get the list of news items, you should able to click and get the news item details

When you click on Author from works, you get a list of authors. If you click on an author, you get a list of works with that author. Where do news items come in? (Some but not all of the works have news items, and those that do have working links to the news items).

**Comment by wkdewey** [comment] 2023-02-20 20:03
Searches from the search bar are only matching the title. I'm not sure how to change this.

**Comment by wkdewey** [comment] 2023-02-20 20:48
> Searches from the search bar are only matching the title. I'm not sure how to change this.

It searches the text field by default, and in Datura it only includes the title by default. If I dump all fields into text (like with Habeas Corpus), then there are more search results.

**Comment by wkdewey** [comment] 2023-02-21 19:55
Some airtable cleanup will be necessary for the browse by country issue. I see United States vs. USA, different spellings of Cote D'Ivoire, one entry with a semicolon instead of a comma, and "Congo, Democratic Republic of" is messing with my attempts to split on a comma.

**Comment by sgar7** [comment] 2023-02-21 20:13
Just cleaned up those instances of misspellings and inconsistencies!

**Comment by elladurham** [comment] 2023-03-06 21:21
> [News Format](https://africanpoetics.unl.edu/inthenews/news/browse/type#): Advertisements, the first one (Multiple Classified Advertising Items)
> What is wrong with these items? Seem to be working fine.

It seems like you go an answer on this one, right, @wkdewey? 
It was on https://africanpoetics.unl.edu/inthenews/news/item/apdp.news.000686 and under "Related Works" the [African Sketches (1834)](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.work.000107)

**Comment by elladurham** [comment] 2023-03-06 21:38
I'm seeing this comment in the list of edits provided by document but not in this open issue list: 

> Are you allowed to format paragraphs in AirTable? There are no blocks of text. Is there a way to do this?
See Featured Poets: [Kofi Awoonor](https://africanpoetics.unl.edu/contemporarypoets/item/ap.per.00025)

Is that an open issue or something that's been answered somewhere else? Apologies if I've overlooked something.

**Comment by wkdewey** [comment] 2023-03-06 22:10
> > [News Format](https://africanpoetics.unl.edu/inthenews/news/browse/type#): Advertisements, the first one (Multiple Classified Advertising Items)
> > What is wrong with these items? Seem to be working fine.
> 
> It seems like you go an answer on this one, right, @wkdewey? It was on https://africanpoetics.unl.edu/inthenews/news/item/apdp.news.000686 and under "Related Works" the [African Sketches (1834)](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.work.000107)

Sarita clarified this to me, and it is working now with my latest changes.

**Comment by wkdewey** [comment] 2023-03-07 18:12
> > **Contemporary African Poets**
> > 
> > * [x]   Under browse by Poet - [remove](https://africanpoetics.unl.edu/contemporarypoets/browse/person.name) the count (1)
> > * [x]   - Rather than A - Z, break it up into A - H, I - L etc.
> > * [x]   Under [browse by country](https://africanpoetics.unl.edu/contemporarypoets/browse/places): we need a country 1 and country 2 which has to be separated. Some people are associated with multiple countries, up to 3. Is there any way to separate the countries so that its just coming up as one on the search?
> > * country of birth, country of residency, country of ethnicity?
> 
> On dev, it looks like 'L-Z' is an incomplete listing, it cuts off after 'K' _(An aside: I'm also wondering if I should follow up on this with the APDP team. It creates kind of a strange/inconsistent user experience doesn't it?)_

I fixed the problem where it was cutting off at the end. Also rebalanced the three alphabetical categories and fixed issues with case and diacritics messing up the sorting.

**Comment by wkdewey** [comment] 2023-03-07 21:34
> I'm seeing this comment in the list of edits provided by document but not in this open issue list:
> 
> > Are you allowed to format paragraphs in AirTable? There are no blocks of text. Is there a way to do this?
> > See Featured Poets: [Kofi Awoonor](https://africanpoetics.unl.edu/contemporarypoets/item/ap.per.00025)
> 
> Is that an open issue or something that's been answered somewhere else? Apologies if I've overlooked something.

An issue has been created for this: #279

**Closed** 2023-03-16 14:26 UTC
